### ISSUE TITLE
Smaller image URL input box

### ISSUE THREAD

**Issue by zjxiaohan** [AllenEllis/EverySingleMonth#7]
Hi. Reddit Yang Gang here. Not a U.S. citizen myself but I love the ideas of Yang and believe that our world will be MUCH better if he gets elected. Thank you so much for your website!

Here's something I came across when I was using the website.

![Screenshot from 2020-01-05 23-09-13](https://user-images.githubusercontent.com/20266703/71782097-40534e00-3011-11ea-91c7-ab8b8477dc99.png)

The input box is pretty long and overlaps with the "SAVE CHANGES" button, which is not ideal.

Instead of hardcoding the size of the input box, I would suggest changing the style to `width: 100%` or something like that. :)

https://github.com/AllenEllis/EverySingleMonth/blob/b95551afbf73512ac7a175afca9f4429ae933867/templates/generated.html#L101

**Comment by AllenEllis** [comment]
Good catch, thanks!
